package com.example.project.Airport;
import java.util.ArrayList;

public class Airport  {
    /** A list of the flights into and out of this airport
     *  Guaranteed not to be null and to contain only non-null entries
     */
    private ArrayList<Flight> allFlights;

    public Airport(ArrayList<Flight> flights) {
        allFlights = flights;
    }

    public ArrayList<Flight> getAllFlights() {
        return allFlights;
    }

    /** Returns the revenue generated by all flights at the airport,
     *  as described in part (a)
     */
    public double getTotalRevenue() {
        double TotalRevenue = 0;
        for (int i = 0; i < allFlights.size(); i++) {
            int capacity = allFlights.get(i).getCapacity();
            int passengers = allFlights.get(i).getNumPassengers();
            double price = allFlights.get(i).getPrice();
            double revenue = passengers * price;

            if (passengers > capacity) {
                revenue -= (passengers - capacity) * price;
            }
            TotalRevenue += revenue;
        }
        return TotalRevenue;
    }

    /** Updates the list of flights by removing certain flights and
     *  returns the total number of passengers whose flights were removed,
     *  as described in part (b)
     */
    public int updateFlights() {
        int totalPassengersRemoved = 0;
        for (int i = 0; i < allFlights.size(); i++) {
            int capacity = allFlights.get(i).getCapacity();
            int passengers = allFlights.get(i).getNumPassengers();
            if (passengers < capacity * .2) {
                totalPassengersRemoved += passengers;
                allFlights.remove(i);
                i--;
            }
        }
        return totalPassengersRemoved;
    }
}